# Generated by Django 4.1.7 on 2023-03-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isMale',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(default='none', max_length=10),
        ),
    ]
