# Generated by Django 4.1.7 on 2023-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_ismale_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodGroup',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
